import * as esbuild from "esbuild";
import process from "process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Core module for testing mind map functionality
if you want to view the source, please visit the github repository of this plugin
*/
`;

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ['src/mindmap-core.ts'],
	bundle: true,
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: true,
	treeShaking: true,
	outfile: 'dist/mindmap-core.js',
	platform: 'node',
	external: [], // No externals for testing
};

try {
	await esbuild.build(buildOptions);
	console.log('✅ Core module built successfully for testing');
	process.exit(0);
} catch (error) {
	console.error('❌ Build failed:', error);
	process.exit(1);
}